version = 1

test_patterns = ["test/**"]

exclude_patterns = [
  "docs/**",
  ".github/**",
  "/ezcv/themes/**",
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"