site_name: ezcv

nav:
    - Home: index.md
    - Included Themes: included-themes.md

theme: readthedocs

repo_url: https://github.com/Descent098/ezcv

site_description: A python-based static site generator for setting up a CV/Resume site

site_author: Kieran Wood

markdown_extensions:
    - codehilite