site_name: ezcv

nav:
    - Home: index.md
    - Quick Start: quick-start.md
    - Included Themes: included-themes.md
    - Usage: usage.md
    - CLI: cli.md
    - Contributor/Developer Docs: contributor-docs.md
    - Theme Development: theme-development.md

theme: readthedocs

repo_url: https://github.com/Descent098/ezcv

site_description: A python-based static site generator for setting up a CV/Resume site

site_author: Kieran Wood

markdown_extensions:
    - codehilite